name: Node.js CI

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-18.04
    name: Test
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "14"
      - run: docker ps
      - run: cd src/api/test && docker-compose ps
      - run: cd src/api && yarn && yarn test
